
function plot_solar_intensity(latitude, day_of_year)
  % plot_solar_intensity - Plots simulated solar intensity vs daytime
  %
  % Syntax:
  %   plot_solar_intensity(latitude, day_of_year)
  %
  % Inputs:
  %   latitude     - Geographic latitude in degrees (-90 to 90)
  %   day_of_year  - Day of the year (1 to 365)
  %
  % Example:
  %   plot_solar_intensity(52, 172) % ~June 21 at latitude 52°N

  % ------------- Fix to AI generated code -------------
  % This code is generated by AI which
  % - interpret wrong north and south latitudes
  % - do not use longitude to make local time shift of sun position
  % - use 1000 W/m2 when mid summer 950 W/m2 in Helsinki (minor effect)
  % - do not notify earth's elliptical path around the sun
  %   (exentricity 0.96, effect about +-11 minutes during year, minor effect)
  % - do not notiy atmospheric "attenuation" of sun intensity at low angles
  % Still this is enough good code for solar panel hobby project

  latitude = -latitude;

  % ---------------- Input Validation ----------------
  if nargin ~= 2
    error("Usage: plot_solar_intensity(latitude, day_of_year)");
  end
  if ~isscalar(latitude) || latitude < -90 || latitude > 90
    error("Latitude must be a scalar between -90 and 90 degrees.");
  end
  if ~isscalar(day_of_year) || day_of_year < 1 || day_of_year > 365
    error("Day of year must be between 1 and 365.");
  end

  % ---------------- Solar Geometry ----------------
  % Declination angle (in radians)
  decl = deg2rad(23.44) * cos(2 * pi * (day_of_year + 10) / 365);

  % Hour angle at sunrise/sunset (in radians)
  ha_sunrise = acos(-tan(deg2rad(latitude)) * tan(decl));

  % Convert to hours
  daylight_hours = (2 * ha_sunrise) * (180/pi) / 15;

  % Time vector (hours)
  t = linspace(0, 24, 500);

  % ---------------- Solar Intensity Model ----------------
  % Assume max intensity at solar noon, zero at sunrise/sunset
  sunrise = 12 - daylight_hours / 2;
  sunset  = 12 + daylight_hours / 2;

  intensity = zeros(size(t));
  for i = 1:length(t)
    if t(i) >= sunrise && t(i) <= sunset
      % Map time to [-pi/2, pi/2] for cosine shape
      phase = (t(i) - 12) / (daylight_hours / 2) * (pi/2);
      intensity(i) = cos(phase); % Normalized intensity
    end
  end

  % Normalize to 1000 W/m² peak
  intensity = intensity * 1000;

  % ---------------- Plot ----------------
  figure;
  plot(t, intensity, 'LineWidth', 2);
  grid on;
  xlabel('Time of Day (hours)');
  ylabel('Solar Intensity (W/m²)');
  title(sprintf('Solar Intensity vs Daytime\nLat: %.1f°, Day: %d', latitude, day_of_year));
  xlim([0 24]);
  ylim([0 1100]);
end

